### ISSUE TITLE
Production checklist

### ISSUE THREAD

**Issue by kristiwalker** [mcclatchy/vfx-project#1]
- [x] Add charts + styling

- [x] Fix text jumping issue

- [x] Check on embedding

- [x] email about URL

- [x] follow up on Omniture

- [x] ask about dynamic preroll tags

- [x] redesign pull quotes

- [x] adjust intro text size

- [x] adjust body copy leading

- [x] about this project section

- [x] related stories section

- [x] change out comments link

- [x] change out share info

- [x] test in Escenic

- [x] complete sources / credits

- [x] navbar shadow

- [x] change out logo dynamically

- [x] thumbnails

- [x] share imgs
